import "./styles/globals.scss";
import { Inter } from "next/font/google";
import ProductContext from "./context/FetchContext";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Task Teste",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={inter.className} suppressHydrationWarning={true}>
                <ProductContext>{children}</ProductContext>
            </body>
        </html>
    );
}
